#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Bodycam_Player

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Mantle_Asset_structs.hpp"
#include "E_Team_structs.hpp"
#include "ALS_Gait_structs.hpp"
#include "ALS_Base_CharacterBP_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "GameMode_structs.hpp"
#include "Bodycam_structs.hpp"
#include "MantleType_structs.hpp"
#include "E_Emote_structs.hpp"
#include "ALS_RotationMode_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Bodycam_Player.Bodycam_Player_C
// 0x13E0 (0x2030 - 0x0C50)
class ABodycam_Player_C final : public AALS_Base_CharacterBP_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Bodycam_Player_C;                   // 0x0C48(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USkeletalMeshComponent*                 PerkController;                                    // 0x0C50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Goggles;                                           // 0x0C58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        WindSounds;                                        // 0x0C60(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        AudioListener;                                     // 0x0C68(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBppfDOFDriverComponent*                BppfDOFDriver;                                     // 0x0C70(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBodycamInteractorComponent*            BodycamInteractor;                                 // 0x0C78(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBodycamRecoilAnimationComponent*       BodycamRecoilAnimation;                            // 0x0C80(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBodycamHeroComponent*                  HeroComponent;                                     // 0x0C88(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        BreathingSounds;                                   // 0x0C90(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAC_BodycamCamera_C*                    AC_BodycamCamera;                                  // 0x0C98(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        FoleySounds;                                       // 0x0CA0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_InventoryComponent_C*               BP_InventoryComponent;                             // 0x0CA8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCameraComponent*                       DeadView;                                          // 0x0CB0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Shadow;                                            // 0x0CB8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Arms;                                              // 0x0CC0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBafCameraAnimation*                    BafCameraAnimation;                                // 0x0CC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAC_BodycamAnimationComponent_C*        AC_BodycamAnimationComponent;                      // 0x0CD0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpringArmComponent*                    Spring_Camera;                                     // 0x0CD8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPostProcessComponent*                  ScreenDroplets;                                    // 0x0CE0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpringArmComponent*                    SpringArms;                                        // 0x0CE8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Censor_Face;                                       // 0x0CF0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpringArmComponent*                    SpringArmBodycamBorders;                           // 0x0CF8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCameraComponent*                       Camera;                                            // 0x0D00(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BodycamBorders;                                    // 0x0D08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         High_Low_NewTrack_0_2170368647D0F769E6870B8F4C8E4061; // 0x0D10(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            High_Low__Direction_2170368647D0F769E6870B8F4C8E4061; // 0x0D14(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D15[0x3];                                      // 0x0D15(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Low;                                               // 0x0D18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_1_NewTrack_0_40651C3A4F4C023FFC170985277DF3DE; // 0x0D20(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_1__Direction_40651C3A4F4C023FFC170985277DF3DE; // 0x0D24(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D25[0x3];                                      // 0x0D25(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_1;                                        // 0x0D28(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_NewTrack_0_C3480EDD48C0FAE4CD939CB14A6E380B; // 0x0D30(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_0__Direction_C3480EDD48C0FAE4CD939CB14A6E380B; // 0x0D34(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D35[0x3];                                      // 0x0D35(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_0;                                        // 0x0D38(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_Alpha_22AE86064266608C0B6BB991AA6C77A5;   // 0x0D40(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline__Direction_22AE86064266608C0B6BB991AA6C77A5; // 0x0D44(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D45[0x3];                                      // 0x0D45(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline;                                          // 0x0D48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FMantle_Asset                          Mantle_2m_Default;                                 // 0x0D50(0x0040)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FMantle_Asset                          Mantle_1m_Default;                                 // 0x0D90(0x0040)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FMantle_Asset                          Mantle_1m_RH;                                      // 0x0DD0(0x0040)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FMantle_Asset                          Mantle_1m_LH;                                      // 0x0E10(0x0040)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FMantle_Asset                          Mantle_1m_2H;                                      // 0x0E50(0x0040)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FMantle_Asset                          Mantle_1m_Box;                                     // 0x0E90(0x0040)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           LandRoll_Default;                                  // 0x0ED0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           GetUpFront_Default;                                // 0x0ED8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           LandRoll_RH;                                       // 0x0EE0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           LandRoll_LH;                                       // 0x0EE8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           LandRoll_2H;                                       // 0x0EF0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           GetUpFront_RH;                                     // 0x0EF8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           GetUpFront_LH;                                     // 0x0F00(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           GetUpFront_2H;                                     // 0x0F08(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           GetUpBack_Default;                                 // 0x0F10(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           GetUpBack_RH;                                      // 0x0F18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           GetUpBack_LH;                                      // 0x0F20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           GetUpBack_2H;                                      // 0x0F28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UTimelineComponent*                     TLine_Camera_Jump;                                 // 0x0F30(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UTimelineComponent*                     TLine_Camera_Land_0;                               // 0x0F38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UTimelineComponent*                     TLine_Reset_Camera;                                // 0x0F40(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Look;                                              // 0x0F48(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Avoidance_Distance;                                // 0x0F58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Holding_Aim_Key;                                   // 0x0F60(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Leaning_Pressed;                                   // 0x0F61(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F62[0x6];                                      // 0x0F62(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Leaning_Target;                                    // 0x0F68(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Leaning_Target_Pressed;                            // 0x0F70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Leaning;                                           // 0x0F78(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Automatically_Leaning;                             // 0x0F79(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F7A[0x6];                                      // 0x0F7A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Corner_Peek_Division;                              // 0x0F80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Leaning_Alpha;                                     // 0x0F88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Current_Leaning_Rotation__Server_;                 // 0x0F90(0x0018)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Leaning_Camera_Offset_Rotation;                    // 0x0FA8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               Smooth_Control_Rotation;                           // 0x0FC0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Leaning_Switched;                                  // 0x0FD8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Can_Lean;                                          // 0x0FD9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FDA[0x6];                                      // 0x0FDA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Leaning_Previous;                                  // 0x0FE0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Current_Control_Rotation_Interp_Speed;             // 0x0FE8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Aiming;                                            // 0x0FF0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Team                                        Team;                                              // 0x0FF1(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_FF2[0x6];                                      // 0x0FF2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        Sound;                                             // 0x0FF8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FPostProcessSettings                   PP_Normal;                                         // 0x1000(0x0700)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FPostProcessSettings                   PP_Night_Vision;                                   // 0x1700(0x0700)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          IsTalking;                                         // 0x1E00(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E01[0x7];                                     // 0x1E01(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 PlayerUserName;                                    // 0x1E08(0x0010)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, RepNotify, HasGetValueTypeHash)
	class ABodycam_Player_C*                      Dot_Owner;                                         // 0x1E18(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, RepNotify, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Breathing_cue;                                     // 0x1E20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        AimingRotationSpeed;                               // 0x1E28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          AimingBloked;                                      // 0x1E30(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E31[0x7];                                     // 0x1E31(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Blured;                                            // 0x1E38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Shake;                                             // 0x1E40(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BlockingDistance;                                  // 0x1E48(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E4C[0x4];                                     // 0x1E4C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        DistanceFromCamera;                                // 0x1E50(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               FinalSmoothRotation;                               // 0x1E58(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	double                                        Yaw_DeltaTime_;                                    // 0x1E70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Pitch_DeltaTime_;                                  // 0x1E78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Throw;                                             // 0x1E80(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E81[0x7];                                     // 0x1E81(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        FlashBangEar;                                      // 0x1E88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               Final_Smooth_Rotation__Replicated_;                // 0x1E90(0x0018)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FVector                                Current_Leaning_Rotation__Client_;                 // 0x1EA8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          BlockLeftLean;                                     // 0x1EC0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          BlockRightLean;                                    // 0x1EC1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          AllowItemDetection;                                // 0x1EC2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1EC3[0x5];                                     // 0x1EC3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               Screen_Droplets_MID;                               // 0x1EC8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	float                                         BloodDropletsIntensity;                            // 0x1ED0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1ED4[0x4];                                     // 0x1ED4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            DamageInstigator;                                  // 0x1ED8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UMaterialInterface>      Screen_Droplets_Parent_Material;                   // 0x1EE0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	double                                        Screen_Center_Strength;                            // 0x1F08(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Screen_Edge_Strength;                              // 0x1F10(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Droplet_Tiling;                                    // 0x1F18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Blur_Radius;                                       // 0x1F20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        NewVar;                                            // 0x1F28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          LightAiming;                                       // 0x1F30(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1F31[0x7];                                     // 0x1F31(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        LightAimingHeight;                                 // 0x1F38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             PoseLeft_Offset;                                   // 0x1F40(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             PoseAim_Offset;                                    // 0x1FA0(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bCharacterIsPossessed;                             // 0x2000(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsSkinSetUp;                                      // 0x2001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HMS_bIsReplicated;                                 // 0x2002(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HMS_bIsLoaded;                                     // 0x2003(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          bDesireAiming;                                     // 0x2004(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bDesireSprinting;                                  // 0x2005(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2006[0x2];                                     // 0x2006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                BordersBaseScale;                                  // 0x2008(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CachedAspectRatio;                                 // 0x2020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AddVoteNextMap(const struct FSTR_VoteNextMapInfo& VoteInfo);
	void ApplyPointDamage(double Damage, double RagdollForce, class FName BoneName, const struct FVector& Location, const struct FVector& ShotFromDirection, class AController* ControllerInstigator, bool DisableHeadShot);
	void Blur(double Distance);
	void BndEvt__Bodycam_Player_WW_SurvivorStatus_K2Node_ComponentBoundEvent_0_BodycamHealth_DeathEvent__DelegateSignature(class AActor* OwningActor);
	void BoneDamage(class FName bone, double Damage, bool DisableHeadShot, double* DamageFinal);
	void Bots_Method_(bool* Bots_Method);
	void BPI_Get_Inventory(class UInventory_C** Inventory);
	struct FTransform BPI_Get_3P_PivotTarget();
	void BPI_Get_3P_TraceParams(struct FVector* TraceOrigin, double* TraceRadius, ETraceTypeQuery* TraceChannel);
	struct FVector BPI_Get_FP_CameraTarget();
	void BreakTimer();
	void Breathing();
	void BroadcastCameraTransitionOnDeath();
	void BulletFly(double Distance, const struct FVector& Location);
	void CanCreateKickVote(bool* CanCreateKickVote_);
	void CanKickThisPlayer_(const class FString& PlayerID, bool* True_);
	void Check_Automatic_Leaning();
	void ClampControlRotation(double YawLimit, double PitchLimit);
	void ClearMap();
	void Cut__Client_();
	void Cut__Server_(class UObject* Target, class FName BoneName, const struct FVector& Location, const struct FVector& ShotFromDirection, class APlayerController* KillerPC);
	void DeployPerk();
	void DestroyVOIP();
	void Event_Ragdoll_End();
	void EventRagdollStart();
	void ExecuteUbergraph_Bodycam_Player(int32 EntryPoint);
	void ExitPerk();
	void ExitPerkAnimations();
	void Final_Smooth_Rotation__Server_(const struct FRotator& FinalSmoothRotation_0);
	void Flashbang(double BaseDamage);
	void Flinch();
	void Get_Added_Rotations(struct FRotator* Value);
	void Get_Avoidance_Trace_Inputs(const struct FVector& Offset, double Avoidance_Distance_0, struct FVector* Start, struct FVector* End);
	struct FVector Get_Forward_Rotation();
	void Get_Stamina(double* Stamina);
	void GetActiveAimPoint(struct FTransform* AimPoint, double* ZPosition);
	void GetActiveGripData(struct FF_GripData* GripData);
	void GetActiveStockOffset(struct FVector* Offset);
	void GetAllowedMap(TArray<TSoftObjectPtr<class UPDA_LevelMetaData_C>>* AllowedMap);
	void GetBlured(double* Blured_0);
	void GetBodycamAnimationComponent(class UAC_BodycamAnimationComponent_C** AC_BodycamAnimationComponent_0);
	void GetBotsAccuracy(struct FVector* TargetLocation, double* CurrentAccuracy, double* BotSkillThreshold, bool* TargetIsPlayer);
	void GetBurnedRef(class USceneComponent** BurnedMesh);
	void GetCameraAnimation(class UBafCameraAnimation** BafCameraAnimation_0);
	void GetCurrentWeaponsGunGame(class FName* CurrentWeaponsGunGame);
	void GetDeadView(class UCameraComponent** DeadViewCameraComponent, class UCameraComponent** BaseCameraComponent);
	void GetFlashBangEffect(double* FlashEffect);
	void GetGameMode(struct FSTR_GamemodeWinInfo* GameMode);
	class UAnimMontage* GetGetUpAnimation(bool RagdollFaceUp_0);
	void GetHealth(double* Health);
	void GetKickedPlayerVoted(TArray<class FString>* KickplayerAlreadyVote);
	struct FMantle_Asset GetMantleAsset(EMantleType MantleType);
	void GetMutePlayer(TArray<class FString>* MutePlayer);
	void GetPcInfo(struct FSTR_PCInfo* PCInfo);
	void GetPhysicsControl(class UPhysicsControlComponent** PhysicsControl_0);
	void GetPlayerConnected(TArray<struct FSTR_PCInfo>* PlayerConnected);
	void GetPlayerKickVote(TArray<struct FSTR_KickVote>* KickVotePlayer);
	void GetPlayerSkin(struct FSTR_TEST* Player_Skin, bool* Valid_);
	void GetRagdollSystem(class UWW_RagdollSystem_C** Ragdoll_System);
	void GetReady_(bool* IsReady_);
	void GetRecoilAnimation(class URecoilAnimationComponent** RecoilAnimation);
	void GetReloadPlayRate(double* PlayRate);
	class UAnimMontage* GetRollAnimation();
	void GetServerSteamID(class FString* SteamID);
	void GetStarterWeapons(TArray<struct FSTR_Loadout>* Weapons);
	void GetSteamID(class FString* SteamID);
	void GetSurvivorStatuts(class UWW_SurvivorStatus_C** SurvivorComponant);
	void GetTeam(E_Team* Team_0);
	void GetTeamList(E_Team Team_0, TArray<struct FSTR_PCInfo>* Info);
	void GetTopScore(TArray<struct FSTR_PCInfo>* TopScore);
	void GetWeaponMesh(class USkeletalMeshComponent** Mesh_0);
	void GetWep(class AWEP_C** WEP_0);
	void HandleTalkStateChanged(bool bIsTalking);
	void Low__FinishedFunc();
	void Low__UpdateFunc();
	void HMS_BeginPlay();
	void HMS_OnActive();
	void HMS_OnDestory();
	void HMS_OnInitialize();
	void HMS_OnPostLoad();
	void HMS_OnPreSave();
	void HMS_OnPreSpawn();
	void IncreaseTremor(double Tremor);
	void Init_PcInfo__Client_();
	void InitDotOwner__Multicast_(class ABodycam_Player_C* DotOwner);
	void InitDotOwner__Server_(class ABodycam_Player_C* Dot_Owner_0);
	void InitOnCharacterLocallyControlled();
	void InitScoreBoard();
	void InitVoteNextMap();
	void InpActEvt_IA_AimWeapon_K2Node_EnhancedInputActionEvent_3(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_AimWeapon_K2Node_EnhancedInputActionEvent_4(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Crouch_K2Node_EnhancedInputActionEvent_7(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Crouch_K2Node_EnhancedInputActionEvent_8(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_FireMode_K2Node_EnhancedInputActionEvent_21(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_22(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_23(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Lean_K2Node_EnhancedInputActionEvent_0(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Lean_K2Node_EnhancedInputActionEvent_1(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Lean_K2Node_EnhancedInputActionEvent_2(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Look_K2Node_EnhancedInputActionEvent_19(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Look_K2Node_EnhancedInputActionEvent_20(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_17(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_18(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Slot1_K2Node_EnhancedInputActionEvent_10(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Slot2_K2Node_EnhancedInputActionEvent_11(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Slot3_K2Node_EnhancedInputActionEvent_12(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Slot4_K2Node_EnhancedInputActionEvent_13(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Slot5_K2Node_EnhancedInputActionEvent_14(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Slot6_K2Node_EnhancedInputActionEvent_15(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Sprint_K2Node_EnhancedInputActionEvent_5(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Sprint_K2Node_EnhancedInputActionEvent_6(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_SwapWeapons_K2Node_EnhancedInputActionEvent_16(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Take_K2Node_EnhancedInputActionEvent_9(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_O_K2Node_InputDebugKeyEvent_0(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void IsDead(bool* Dead_);
	void IsDestroyabe_(bool* Destroyable_);
	void IsPlayerWinning(bool* Yes_);
	void IsReady_(bool IsReady__0);
	void IsStress(bool* Yes_);
	void IsTalking_(bool* IsTalking__0);
	bool K2_CustomUpdateGroundedRotation();
	void K2_OnEndCrouch(float HalfHeightAdjust, float ScaledHalfHeightAdjust);
	void K2_OnStartCrouch(float HalfHeightAdjust, float ScaledHalfHeightAdjust);
	void Kick_(const struct FSTR_PCInfo& Target);
	void KickPlayer(const struct FSTR_KickVote& PlayerInfo);
	void MSG_ChatGetConnectedPlayers(TArray<class AController*>* Players);
	void MSG_ChatGetPlayerID(int32* PlayerID);
	void MSG_ChatGetTeamID(int32* TeamID);
	void MSG_ChatGetUsername(bool* Success_, class FText* Username);
	void MSG_ChatPlayEmote(E_Emote EmoteToPlay);
	void MSG_ChatRequestPlayerID(int32* PlayerID, bool* Success_);
	void Multi_PlayerEmote(E_Emote EmoteToPlay);
	void MuteID(const class FString& SteamID);
	void NewKickVote(const struct FSTR_PCInfo& Target);
	void OnLanded(const struct FHitResult& Hit);
	void OnPlayerDeath(const struct FSTR_PCInfo& PC);
	void OnRep_bCharacterIsPossessed();
	void OnRep_Dot_Owner();
	void OnRep_HMS_bIsLoaded();
	void OnRep_PlayerUserName();
	void OnTrySelectTeam(E_Team Team_0);
	void Play_Sounds__Multicast_(class USoundBase* Sound_0);
	void Play_Sounds__Server_(class USoundBase* Sound_0);
	void PlayCameraShake(TSubclassOf<class ULegacyCameraShake> ShakeClass, float Scale);
	void PlaySoundLocal(class USoundCue* Audio);
	void ReceiveBeginPlay();
	void ReceiveControllerChanged(class AController* OldController, class AController* NewController);
	void ReceiveDestroyed();
	void ReceivePossessed(class AController* NewController);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveUnpossessed(class AController* OldController);
	void Reference_WBP_Map_Vote(class UObject* WBP_Map_Vote);
	void RefreshMapVoterPlayerID();
	void Respawn(double duration, const struct FSTR_PCInfo& Info);
	void S_CurrentLeaningRotation(const struct FVector& Current_Leaning_Rotation);
	void ScaleBordersToAspectRatio();
	void Server___Cheat_KillMyself();
	void Server___Cheat_ToggleInfiniteAmmo();
	void Server_PlayerEmote(E_Emote EmoteToPlay);
	void ServerTravel(double Delay, const class FString& Level);
	void Set_Bomb(TSoftObjectPtr<class ABombe_C> Bomb);
	void SetEquippedWeapon(const class AWEP_C*& WeaponRef);
	void SetUpCharacterMeshesVisibility();
	bool Should_Be_Aiming();
	void Slomo(double Slomo_0);
	void StartBloodOnCamera();
	void Talk(bool IsTalking_0);
	void Test_PlayMontageByName(const class FString& MontageName);
	void Timeline_0__FinishedFunc();
	void Timeline_0__UpdateFunc();
	void Timeline_1__FinishedFunc();
	void Timeline_1__UpdateFunc();
	void Timeline__FinishedFunc();
	void Timeline__UpdateFunc();
	void tk(float duration);
	void Trace_for_Forward_Blocked();
	void TryPlayVOIPMontage(class UAnimMontage* AnimMontage);
	void Update_Leaning_Values();
	void Update_Vote_Timer_Text(double TimerIndex);
	void UpdateGamemode(EGameMode GameMode);
	void UpdateKickVote(const struct FSTR_PCInfo& Target, bool Yes_);
	void UpdateMapSelection(class FName Selected_Level_Name, int32 Index_0);
	void UpdateModeInfo();
	void UpdatePCInfo(const struct FSTR_PCInfo& PCInfo);
	void UpdatePlayerUserName__Multicast_(const class FString& InString);
	void UpdatePlayerUserName__Server_(const class FString& InString);
	void UpdateRotationModeWithDelay(double Delay, EALS_RotationMode NewRotationMode);
	void UpdateScore(const struct FSTR_Score& Score);
	void UpdateSkin(TSoftObjectPtr<class USkeletalMesh> NewSkin);
	void UpdateTeamXP(int32 RPoints, int32 RanksPoints, bool AccessReward_, bool Winner_);
	void UpdateTransitionMap();
	void UpdateWarning(const class FString& String);
	void UserConstructionScript();
	void WindCamera();

	bool HMS_IsLoaded() const;
	bool HMS_IsReplicated() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Bodycam_Player_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Bodycam_Player_C")
	}
	static class ABodycam_Player_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABodycam_Player_C>();
	}
};
DUMPER7_ASSERTS_ABodycam_Player_C;

SDK_NAMESPACE_END
