#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BodycamPlayerCameraManager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Bodycam_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BodycamPlayerCameraManager.BP_BodycamPlayerCameraManager_C
// 0x0020 (0x25C0 - 0x25A0)
class ABP_BodycamPlayerCameraManager_C final : public ABodycamPlayerCameraManager
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x25A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         EndRoundCameraEffect_EffectIntensity_39D335B84C96408AD495E48A655AF0D9; // 0x25A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            EndRoundCameraEffect__Direction_39D335B84C96408AD495E48A655AF0D9; // 0x25AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25AD[0x3];                                     // 0x25AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     EndRoundCameraEffect;                              // 0x25B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCAM_EndRound_C*                        EndRoundCamModifier;                               // 0x25B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void EndRoundCameraEffect__FinishedFunc();
	void EndRoundCameraEffect__UpdateFunc();
	void ExecuteUbergraph_BP_BodycamPlayerCameraManager(int32 EntryPoint);
	float GetShakeIntensityFromSettings();
	void InitEndRoundCameraEffect();
	void ResetEndRoundCameraEffect();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BodycamPlayerCameraManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BodycamPlayerCameraManager_C")
	}
	static class ABP_BodycamPlayerCameraManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BodycamPlayerCameraManager_C>();
	}
};
DUMPER7_ASSERTS_ABP_BodycamPlayerCameraManager_C;

SDK_NAMESPACE_END
