#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC_Bodycam

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "E_Team_structs.hpp"
#include "PC_BodycamBase_classes.hpp"
#include "STR_KillInfo_structs.hpp"
#include "GM_Statue_structs.hpp"
#include "SteamCorePro_structs.hpp"
#include "GameMode_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PC_Bodycam.PC_Bodycam_C
// 0x0118 (0x09F0 - 0x08D8)
class APC_Bodycam_C final : public APC_BodycamBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_PC_Bodycam_C;                       // 0x08D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_LoadoutSaveManagerComponent_C*      BP_LoadoutSaveManagerComponent;                    // 0x08E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UHUD_Character_C*                       HUD_Character;                                     // 0x08E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UHUD_TransitionLevels_C*                HUD_Transition;                                    // 0x08F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UHUD_ScoreBoardMenu_C*                  HUD_ScoreBoard;                                    // 0x08F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FString                                 SteamID__Server_;                                  // 0x0900(0x0010)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class AGT_Bodycam_C*                          GT_Bodycam;                                        // 0x0910(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	E_Team                                        Team;                                              // 0x0918(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_919[0x7];                                      // 0x0919(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UHUD_Warning_C*                         HUD_Warning;                                       // 0x0920(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         SteamIDMuted;                                      // 0x0928(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   Kick_Reason;                                       // 0x0938(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UKickOverlay_C*                         KickOverlay;                                       // 0x0948(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         PlayerVoteToKick;                                  // 0x0950(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UAudioComponent*                        EndRoundSounds;                                    // 0x0960(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         AttempsToSpawn;                                    // 0x0968(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_96C[0x4];                                      // 0x096C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         PlayerWhoITriedToKick;                             // 0x0970(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          IsSwapingGun;                                      // 0x0980(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_981[0x3];                                      // 0x0981(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CurrentWeaponsGunGame;                             // 0x0984(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         FriendCount;                                       // 0x098C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FSTR_KillInfo>                  Stats_Kill_Info;                                   // 0x0990(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                        CurrentPlaytime;                                   // 0x09A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MinPlaytimeToAccessReward;                         // 0x09A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          AccessReward;                                      // 0x09B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Winner_;                                           // 0x09B1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsDeadDuringMatch;                                 // 0x09B2(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9B3[0x1];                                      // 0x09B3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         RoundKills;                                        // 0x09B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   DroneClass;                                        // 0x09B8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(int32 RankScore, int32 ReissadScore)> PropagateXPReward;           // 0x09E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void Add_New_Player(E_Team FriendTeam, class AController* PC, const struct FSTR_PCStats& Stats, const struct FDataTableRowHandle& Skin_Info, const struct FDataTableRowHandle& Badge_Info, struct FSTR_PCInfo* PlayerInfo);
	void AddVoteNextMap(const struct FSTR_VoteNextMapInfo& VoteInfo);
	void Bots_Method_(bool* Bots_Method);
	void BPI_Get_Inventory(class UInventory_C** Inventory);
	void BreakTimer();
	void CanCreateKickVote(bool* CanCreateKickVote_);
	void CanKickThisPlayer_(const class FString& PlayerID, bool* True_);
	void ClearMap();
	void ClearMap__Client_();
	void Event_Ragdoll_End();
	void EventRagdollStart();
	void ExecuteUbergraph_PC_Bodycam(int32 EntryPoint);
	void Find_Best_Spawn_Point(const class FString& Name_0, struct FTransform* FarestTransform_return);
	void FindPlayerSpawn(const class FString& Name_0, struct FTransform* SpawnTransform);
	void Get_Stamina(double* Stamina);
	void GetAllowedMap(TArray<TSoftObjectPtr<class UPDA_LevelMetaData_C>>* AllowedMap);
	void GetBlured(double* Blured);
	void GetBotsAccuracy(struct FVector* TargetLocation, double* CurrentAccuracy, double* BotSkillThreshold, bool* TargetIsPlayer);
	void GetBurnedRef(class USceneComponent** BurnedMesh);
	void GetCurrentRank(class FText* CurrentRank, int32* Rank_, int32* RankScore, int32* Connection_Streak);
	void GetCurrentWeaponsGunGame(class FName* CurrentWeaponsGunGame_0);
	void GetDeadView(class UCameraComponent** DeadViewCameraComponent, class UCameraComponent** BaseCameraComponent);
	void GetFlashBangEffect(double* FlashEffect);
	void GetFriendsTeam(E_Team* Team_0);
	void GetGameMode(struct FSTR_GamemodeWinInfo* GameMode);
	void GetHealth(double* Health);
	void GetKickedPlayerVoted(TArray<class FString>* KickplayerAlreadyVote);
	void GetMutePlayer(TArray<class FString>* MutePlayer);
	void GetNewRank(class FText* Name_0, class UTexture2D** Image, int32* RankScore, int32* RankPosition, int32* RankDivision, double* PreviousRankProgress, double* RankProgress, bool* NewRank_, struct FSlateColor* Color, int32* Rank_Integer);
	void GetPcInfo(struct FSTR_PCInfo* PCInfo);
	void GetPhysicsControl(class UPhysicsControlComponent** PhysicsControl);
	void GetPlayerConnected(TArray<struct FSTR_PCInfo>* PlayerConnected);
	void GetPlayerKickVote(TArray<struct FSTR_KickVote>* KickVotePlayer);
	void GetPlayerSkin(struct FSTR_TEST* Player_Skin, bool* Valid_);
	void GetRagdollSystem(class UWW_RagdollSystem_C** Ragdoll_System);
	void GetReady_(bool* IsReady_);
	void GetReloadPlayRate(double* PlayRate);
	void GetServerSteamID(class FString* SteamID);
	void GetStarterWeapons(TArray<struct FSTR_Loadout>* Weapons);
	void GetSteamID(class FString* SteamID);
	void GetSurvivorStatuts(class UWW_SurvivorStatus_C** SurvivorComponant);
	void GetTeam(E_Team* Team_0);
	void GetTeamList(E_Team Team_0, TArray<struct FSTR_PCInfo>* Info);
	void GetTopScore(TArray<struct FSTR_PCInfo>* TopScore);
	void GetWep(class AWEP_C** WEP);
	void GunGameKill();
	void HandleMatchEnded(class UBodycamGI_C* GameInstance, bool Won);
	void Init_SteamInfo();
	void InitHudPC();
	void InitPlayerRank__Client(const class FString& SteamID);
	void InitScoreBoard();
	void InitVoteNextMap();
	void Is_Spawn_Point_Valid(const struct FTransform& Spawn_Transform, bool* Valid_);
	void IsDead(bool* Dead_);
	void IsDestroyabe_(bool* Destroyable_);
	void IsPlayerWinning(bool* Yes_);
	void IsReady_(bool IsReady__0);
	void IsStress(bool* Yes_);
	void IsTalking_(bool* IsTalking__0);
	void Kick_Player__server_(const struct FSTR_KickVote& Player_info);
	void Kick_(const struct FSTR_PCInfo& Target);
	void KickPlayer(const struct FSTR_KickVote& PlayerInfo);
	void KickPlayer__Client_(const struct FSTR_KickVote& Player_info);
	void KickVote(bool Yes_);
	void KickVote__Server_(const struct FSTR_PCInfo& Player_info, bool Yes_);
	void MSG_AVP_GetPlayerUsername(bool* Success_, class FText* Username);
	void MSG_AVP_GetWidgetVoice(class UWidgetComponent** WidgetVoiceRef);
	void MuteID(const class FString& SteamID);
	void NewKickVote(const struct FSTR_PCInfo& Target);
	void OnCallback_061AA0BF40D36914D50DAE8E114F95C6();
	void OnLoaded_56027CFC46D66F91EB336D92F414B472(TSubclassOf<class UObject> Loaded);
	void OnPlayerDeath(const struct FSTR_PCInfo& PC);
	void OnTrySelectTeam(E_Team Team_0);
	void Stop_End_Round_Sound__Client_(bool Stop_);
	void PlaySound__Local_(class USoundBase* Sound);
	void PlaySoundLocal(class USoundCue* Audio);
	void ReceiveBeginPlay();
	void ReceivePossess(class APawn* PossessedPawn);
	void Reference_WBP_Map_Vote(class UObject* WBP_Map_Vote);
	void RefreshMapVoterPlayerID();
	void RequestUpdateLobbyMaxPlayers(int32 NewLobbyMaxPlayers);
	void Respawn(double duration, const struct FSTR_PCInfo& Info);
	void Respawn__Server_(EGM_Statue GM_Statue, E_Team Team_0);
	void ServerTravel(double Delay, const class FString& Level);
	void Set_Bomb(TSoftObjectPtr<class ABombe_C> Bomb);
	void SetEquippedWeapon(const class AWEP_C*& WeaponRef);
	void SetSteamID__Server_(const class FString& PCInfo, E_Team Team_0, class AController* PC, const struct FSTR_PCStats& Item_Stats, const struct FDataTableRowHandle& Skin_Info, const struct FDataTableRowHandle& Badge_Info);
	void ShowKickedFromPartyNotification();
	void Slomo(double Slomo_0);
	void Talk(bool IsTalking);
	void Update_ControlRotation(const struct FRotator& NewRotation);
	void Update_Death(int32 Death, bool Set);
	void Update_Death__server_(int32 Death, bool Set);
	void Update_Kill(const struct FSTR_KillInfo& KillInfo);
	void Update_Kill__server_(const struct FSTR_KillInfo& KillInfo);
	void Update_Score__Client_(const struct FSTR_Score& Score);
	void Update_StartingMatch__HUD_PC_();
	void Update_Team_XP__Client_(int32 RPoints, int32 RanksPoints, bool AccessReward_, bool Winner__0);
	void Update_Vote_Timer_Text(double TimerIndex);
	void Update_Warning__Client_(const class FString& InputPin);
	void UpdateAccessReward(bool ServerAllowedReward);
	void UpdateGamemode(EGameMode GameMode);
	void UpdateKickVote(const struct FSTR_PCInfo& Target, bool Yes_);
	void UpdateMapSelection(class FName Selected_Level_Name, int32 Index_0);
	void UpdateModeInfo();
	void UpdateNoMercyAchievement();
	void UpdatePCInfo(const struct FSTR_PCInfo& PCInfo);
	void UpdatePlayerRank__Server_(int32 Stats_Rank, int32 Stats_XP);
	void UpdatePlayTime();
	void UpdateScore(const struct FSTR_Score& Score);
	void UpdateTeamXP(int32 RPoints, int32 RanksPoints, bool AccessReward_, bool Winner__0);
	void UpdateTransitionHud__client_();
	void UpdateTransitionMap();
	void UpdateWarning(const class FString& String);
	void UpdateXp(int32 xp);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PC_Bodycam_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PC_Bodycam_C")
	}
	static class APC_Bodycam_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APC_Bodycam_C>();
	}
};
DUMPER7_ASSERTS_APC_Bodycam_C;

SDK_NAMESPACE_END
